### ISSUE TITLE
Unable to get some blocks from Rustic and Primal tech to drop themselves

### ISSUE THREAD

**Issue by charlescannon** [tyra314/ToolProgression#50] opened 2018-12-11 23:55 UTC
The blocks in question are, alchemical retort and drying basin from rustic and clay kiln and stone grill from primal tech. It shows the mining level null=-1 and setting the cannot break without proper tool allows me to break the block but none of the four blocks drop as items.

**Comment by tyra314** [comment] 2018-12-17 21:17
I tried it with v1.6.3 and this config entry: `S:"rustic:retort:*"=null=-1` and it works fine. Have you put the change in the `block_overwrites.cfg` file?

**Comment by charlescannon** [comment] 2018-12-21 10:35
I don't have asterisks for retorts it popped with numbers I will add that line in see if it fixes it. thank you.

**Comment by charlescannon** [comment] 2018-12-21 14:36
I also removed the retort:0 through 4 and added retort:*, redownloaded both mods(redid block overrides), and made sure to play with just the two mods and for whatever reason it doesn't drop retorts as an item.

I tried changing another block, this time minecraft:stone, it does same thing as the retort change the mining level to null but doesn't drop anything.

**Comment by tyra314** [comment] 2018-12-21 16:41
So, if I understand you correctly, you want to change blocks, which need tools to harvest them such that you can harvest them with bare hands? And then the loot isn't dropped?

Can you post the following information:

- Forge version
- The version of the mods involved
- The contents of the `block_overwrite.cfg` file

**Comment by charlescannon** [comment] 2018-12-22 06:42
Forge 23.14.5.2772
progression 1.6.3
Rustic 1.0.12
tea the story 3.2.6-B9
Tough as Nails 3.1.0.139 

https://docs.google.com/document/d/1RRl9B22Jr6-jtBXLob_M8cW6IX6mgiLNcz8AfPBpvsk/edit?usp=sharing

Rather large number of edits were made so the file is too big for github/pastebin.

**Comment by tyra314** [comment] 2018-12-24 00:16
Okay, one thing first, don't just copy over all entries from the block.cfg. Having so many entries in the overwrites file should be a severe performance degradation in itself and may already be the cause for your problems. Only add actual changes to the overwrites files.

**Comment by charlescannon** [comment] 2018-12-24 05:18
Oh, I was not aware that was intensive, I will be sure to trim it down on my next update. 

I had sent my modpack file since more information about which blocks I changed. But I had tested it with just progression and rustic installed that file had one test of 

   S:"rustic:retort:*"=null=-1

and a second test of 

    # rustic:retort:0 [default: pickaxe=0]
    S:"rustic:retort:0"=null=-1

    # rustic:retort:1 [default: pickaxe=0]
    S:"rustic:retort:1"=null=-1

    # rustic:retort:2 [default: pickaxe=0]
    S:"rustic:retort:2"=null=-1

    # rustic:retort:3 [default: pickaxe=0]
    S:"rustic:retort:3"=null=-1

Both tell me the object is null and allows me to break it with the don't allow breaking without proper tools setting one. Just nothing drops.

I also tested it with tools. It breaks and doesn't drop items with shovel, hoe or axe, but will drop with a pickaxe.

**Comment by tyra314** [comment] 2018-12-29 13:44
This should be fixed in the [version 1.6.4](https://minecraft.curseforge.com/projects/tool-progression/files/2653599). Thank you for pointing it out.

**Closed by tyra314** 2018-12-29 13:44 UTC
Labels: bug

**Comment by charlescannon** [comment] 2018-12-29 22:17
Awesome, thanks I just updated, everything I changed drops like expected thank you.
