### ISSUE TITLE
"Materials and You" shows harvest level names incorrectly after changing B:tconstruct in config

### ISSUE THREAD

**Issue by TCreopargh** [tyra314/ToolProgression#70] opened 2020-09-28 11:18 UTC
So I changed the B:tconstruct=true line in config from true to false to disable the diamond and emerald modifier overwrites and also to fix a bug with another mod (This option conflicts with the Draconic Evolution tools Tinkers' Evolution mod for some weird reason), but I noticed that when I toggle this option off, the harvest level names shown in "Materials and You"(TCon guide book) does not apply the changes I made, it only shows vanilla harvest level names instead. 
It worked as intended before I turned this off, which shows my custom harvest level names.
I don't think it's the intended behavior, this option should only affect the emerald and diamond modifiers.

**Comment by tyra314** [comment] 2021-04-07 09:47
Duplicate of #23

**Closed by tyra314** 2021-04-07 09:47 UTC
