### ISSUE TITLE
Blocks Requiring TPR reload on each game launch.

### ISSUE THREAD

**Issue by edenhack** [tyra314/ToolProgression#56] opened 2019-03-28 03:59 UTC
The general problem is that all blocks are stopping at harvest level 6 on game launch. After a tpr reload command they will all appear correctly up to harvest level 13 (my max tier) but this is required at the start of each launch of a session. Not sure if a multimc console dump would be of assistance for sourcing this issue.

**Comment by edenhack** [comment] 2019-03-29 08:07
I would like to also note that because /tpr reload only works in single player. There is no way to make a server recognize the updated material harvest levels... Thus all of my server's harvest levels stop at 7.

**Comment by tyra314** [comment] 2019-03-30 12:52
Do you have any other mods like tpr in your modpack?

**Comment by edenhack** [comment] 2019-03-30 14:04
I had a conflict between tweakers construct and tpr for harvest level of tools. but tweakers construct doesn't effect block/oredict material levels. I have craft tweaker installed but i have no zenscripts that involve materials either.  Here is my mod list, I don't believe anything in here is messing with material traits other than tpr after a few go overs of the list https://pastebin.com/h5fWdCeu

**Comment by tyra314** [comment] 2019-03-30 17:17
I checked your list and haven't spotted any problematic mod myself. However, with TPr alone, I'm not able to reproduce this. So I'm still convinced, some other mod is overwriting the settings. Especially, if it works after the reload...

**Comment by edenhack** [comment] 2019-03-30 17:18
I understand, I'll do a thorough walkthrough with my mods and see. If i find out what is causing it I will post back a response.

**Comment by edenhack** [comment] 2019-03-30 17:53
It seems to be on my end with how I've written the oreDict overwrites? Even though on a single player map they would work and overwrite the oredict entries after a /tpr reload command usage? MultMC console shows the inisilazation of toolprogressions, it applies my mining levels, then fails to apply my oredict overwrites. Can I post my overwrite file and get confirmation on if something is incorrect. I went over the wiki multiple times and i cannot fathom what I might have done to cause an issue.

**Comment by edenhack** [comment] 2019-03-30 18:00
It seems to apply my overwrites at the very end for just minecraft oredict refrenses. Is there anything else I'm suppose to apply other than S:"ore:oreCopper"=pickaxe=2 if i want to overwrite the mining level of a modded block?

**Comment by tyra314** [comment] 2019-03-30 18:33
Oh, I'm sorry. There is the elephant in the room: #53 

I presume your running into the same issue.

**Comment by tyra314** [comment] 2019-03-30 18:36
Try to make an overwrite for a specific block instead of oredict, that should do it for now

**Comment by tyra314** [comment] 2019-03-30 20:20
This should be fixed in the upcoming [version 1.6.6](https://minecraft.curseforge.com/projects/tool-progression/files/2693458)

**Closed by tyra314** 2019-03-30 20:20 UTC
Labels: bug, duplicate
