### ISSUE TITLE
Ex Nihilo compat

### ISSUE THREAD

**Issue by NillerMedDild** [tyra314/ToolProgression#24] opened 2018-01-03 09:54 UTC
Hello!

I've noticed that the hammers from Ex Nihilo Adcensio and Ex Compressum don't show up in the "tools.cfg" file. I can manually add them to "tool_overwrites" just fine. Could you fix this please? :)

**Comment by tyra314** [comment] 2018-01-03 11:15
Are we talking about 1.12.x here? If it just doesn't show up but still works, I won't go back to 1.11.2 for a fix.

**Comment by tyra314** [comment] 2018-01-03 13:45
Okay, after looking into it, I think this is intended behavior. Only tools in the original minecraft-sense are listed in the `tools.cfg` file. If you think about it, the hammer and the crook aren't tools in the Minecraft sense. A hammer can be used to hammer dust, sand, gravel, and cobble blocks. This means it can harvest specific blocks, which have different tool classes: none, shovel, shovel, and pickaxe, respectively. But the hammer can't harvest all blocks in the same tool class. Therefore, the hammer isn't a tool in the original Minecraft sense.

Having said that, there is still another issue here, which is way more severe. 
As the hammer isn't a tool in the traditional sense, Tool Progression prevents it from being used as intended. You can't assign multiple tool classes to one block, so you can't fix this with just adding a new tool class to the hammers and blocks. And giving the hammer the tool classes it would need, makes it also usable as a pickaxe and shovel, which is also not intended. I'll look into that eventually.

**Comment by tyra314** [comment] 2018-01-03 15:31
Fixed in [1.4.7](https://minecraft.curseforge.com/projects/tool-progression/files/2516432).

**Closed by tyra314** 2018-01-03 15:31 UTC
Labels: bug

**Comment by NillerMedDild** [comment] 2018-01-03 17:22
Cool, thank you.
